// <auto-generated />
using Danny.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Danny.Core.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230929034303_tohasmany")]
    partial class tohasmany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Danny.Core.Models.MKline", b =>
                {
                    b.Property<string>("StockCode")
                        .HasColumnType("text")
                        .HasColumnName("stock_code");

                    b.Property<decimal>("Timestamp")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("timestamp");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<double>("Chg")
                        .HasColumnType("double precision")
                        .HasColumnName("chg");

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<double>("Percent")
                        .HasColumnType("double precision")
                        .HasColumnName("percent");

                    b.Property<double>("Turnoverrate")
                        .HasColumnType("double precision")
                        .HasColumnName("turnoverrate");

                    b.Property<decimal>("Volumn")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("volumn");

                    b.HasKey("StockCode", "Timestamp")
                        .HasName("pk_m_kline");

                    b.ToTable("m_kline", (string)null);
                });

            modelBuilder.Entity("Danny.Core.Models.Stock", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<int>("MarketCode")
                        .HasColumnType("integer")
                        .HasColumnName("market_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_stocks");

                    b.ToTable("stocks", (string)null);
                });

            modelBuilder.Entity("Danny.Core.Models.MKline", b =>
                {
                    b.HasOne("Danny.Core.Models.Stock", "Stock")
                        .WithMany("MKlines")
                        .HasForeignKey("StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_m_kline_stocks_stock_temp_id");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Danny.Core.Models.Stock", b =>
                {
                    b.Navigation("MKlines");
                });
#pragma warning restore 612, 618
        }
    }
}
